# Table of Contents
 <p><div class="lev1"><a href="#NumPy-Basics:-Arrays-and-Vectorized-Computation"><span class="toc-item-num">1&nbsp;&nbsp;</span>NumPy Basics: Arrays and Vectorized Computation</a></div><div class="lev2"><a href="#The-NumPy-ndarray:-a-multidimensional-array-object"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>The NumPy ndarray: a multidimensional array object</a></div><div class="lev3"><a href="#Creating-ndarrays"><span class="toc-item-num">1.1.1&nbsp;&nbsp;</span>Creating ndarrays</a></div><div class="lev3"><a href="#Data-Types-for-ndarrays"><span class="toc-item-num">1.1.2&nbsp;&nbsp;</span>Data Types for ndarrays</a></div><div class="lev3"><a href="#Operations-between-arrays-and-scalars"><span class="toc-item-num">1.1.3&nbsp;&nbsp;</span>Operations between arrays and scalars</a></div><div class="lev3"><a href="#Basic-indexing-and-slicing"><span class="toc-item-num">1.1.4&nbsp;&nbsp;</span>Basic indexing and slicing</a></div><div class="lev4"><a href="#Indexing-with-slices"><span class="toc-item-num">1.1.4.1&nbsp;&nbsp;</span>Indexing with slices</a></div><div class="lev3"><a href="#Boolean-indexing"><span class="toc-item-num">1.1.5&nbsp;&nbsp;</span>Boolean indexing</a></div><div class="lev3"><a href="#Fancy-indexing"><span class="toc-item-num">1.1.6&nbsp;&nbsp;</span>Fancy indexing</a></div><div class="lev3"><a href="#Transposing-arrays-and-swapping-axes"><span class="toc-item-num">1.1.7&nbsp;&nbsp;</span>Transposing arrays and swapping axes</a></div><div class="lev2"><a href="#Universal-Functions:-Fast-element-wise-array-functions"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>Universal Functions: Fast element-wise array functions</a></div><div class="lev2"><a href="#Data-processing-using-arrays"><span class="toc-item-num">1.3&nbsp;&nbsp;</span>Data processing using arrays</a></div><div class="lev3"><a href="#Expressing-conditional-logic-as-array-operations"><span class="toc-item-num">1.3.1&nbsp;&nbsp;</span>Expressing conditional logic as array operations</a></div><div class="lev3"><a href="#Mathematical-and-statistical-methods"><span class="toc-item-num">1.3.2&nbsp;&nbsp;</span>Mathematical and statistical methods</a></div><div class="lev3"><a href="#Methods-for-boolean-arrays"><span class="toc-item-num">1.3.3&nbsp;&nbsp;</span>Methods for boolean arrays</a></div><div class="lev3"><a href="#Sorting"><span class="toc-item-num">1.3.4&nbsp;&nbsp;</span>Sorting</a></div><div class="lev3"><a href="#Unique-and-other-set-logic"><span class="toc-item-num">1.3.5&nbsp;&nbsp;</span>Unique and other set logic</a></div><div class="lev2"><a href="#File-input-and-output-with-arrays"><span class="toc-item-num">1.4&nbsp;&nbsp;</span>File input and output with arrays</a></div><div class="lev3"><a href="#Storing-arrays-on-disk-in-binary-format"><span class="toc-item-num">1.4.1&nbsp;&nbsp;</span>Storing arrays on disk in binary format</a></div><div class="lev3"><a href="#Saving-and-loading-text-files"><span class="toc-item-num">1.4.2&nbsp;&nbsp;</span>Saving and loading text files</a></div><div class="lev2"><a href="#Linear-algebra"><span class="toc-item-num">1.5&nbsp;&nbsp;</span>Linear algebra</a></div><div class="lev2"><a href="#Random-number-generation"><span class="toc-item-num">1.6&nbsp;&nbsp;</span>Random number generation</a></div><div class="lev2"><a href="#Example:-Random-Walks"><span class="toc-item-num">1.7&nbsp;&nbsp;</span>Example: Random Walks</a></div><div class="lev3"><a href="#Simulating-many-random-walks-at-once"><span class="toc-item-num">1.7.1&nbsp;&nbsp;</span>Simulating many random walks at once</a></div>

# NumPy Basics: Arrays and Vectorized Computation

In [9]:
%matplotlib inline

In [10]:
from __future__ import division
from numpy.random import randn
import numpy as np
np.set_printoptions(precision=4, suppress=True)

## The NumPy ndarray: a multidimensional array object

In [11]:
data = randn(2, 3)

In [12]:
data

array([[ 1.4048,  0.8311, -0.1193],
       [-1.5136, -0.8502,  0.5059]])

In [13]:
data * 10

array([[ 14.0479,   8.3115,  -1.1927],
       [-15.136 ,  -8.5021,   5.0589]])

In [14]:
data + data

array([[ 2.8096,  1.6623, -0.2385],
       [-3.0272, -1.7004,  1.0118]])

- An ndarray is a generic multidimensional container for homogeneous data; that is, all of the elements must be the same type. Every array has a shape, a tuple indicating the size of each dimension, and a dtype, an object describing the data type of the array.

In [15]:
data.shape

(2, 3)

In [16]:
data.dtype

dtype('float64')

### Creating ndarrays

In [17]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([ 6. ,  7.5,  8. ,  0. ,  1. ])

In [19]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
print arr2
print arr2.ndim
print arr2.shape

[[1 2 3 4]
 [5 6 7 8]]
2
(2, 4)


In [20]:
print arr1.dtype
print arr2.dtype

float64
int64


- In addition to np.array, there are a number of other functions for creating new arrays. As examples, zeros and ones create arrays of 0’s or 1’s, respectively, with a given length or shape. empty creates an array without initializing its values to any particular value. To create a higher dimensional array with these methods, pass a tuple for the shape.

In [21]:
print np.zeros(10)
print np.zeros((3, 6))
print np.empty((2, 3, 2))

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[[ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]]
[[[ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]]

 [[ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]]]


- arange is an array-valued version of the built-in Python range function

In [22]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

- Array creation functions

| Function | Description |
|--------------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| array | Convert input data (list, tuple, array, or other sequence type) to an ndarray either by inferring a dtype or explicitly specifying a dtype. Copies the input data by default. |
| asarray | Convert input to ndarray, but do not copy if the input is already an ndarray |
| arange | Like the built-inrangebut returns an ndarray instead of a list. |
| ones, ones_like | Produce an array of all 1’s with the given shape and dtype. ones_like takes another array and produces a ones array of the same shape and dtype. |
| zeros, zeros_like | Likeonesandones_likebut producing arrays of 0’s instead |
| empty, empty_like | Create new arrays by allocating new memory, but do not populate with any values like ones and zeros |
| eye, identity | Create a square N x N identity matrix (1’s on the diagonal and 0’s elsewhere) |

### Data Types for ndarrays

In [24]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)
print arr1.dtype
print arr2.dtype

float64
int32


- You can explicitly convert or cast an array from one dtype to another using ndarray’s astype method:

In [25]:
arr = np.array([1, 2, 3, 4, 5])
print arr.dtype
float_arr = arr.astype(np.float64)
print float_arr.dtype

int64
float64


In [28]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr

array([  3.7,  -1.2,  -2.6,   0.5,  12.9,  10.1])

In [29]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [30]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
numeric_strings.astype(float)

array([  1.25,  -9.6 ,  42.  ])

In [31]:
int_array = np.arange(10)
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)
int_array.astype(calibers.dtype)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

- There are shorthand type code strings you can also use to refer to a dtype:

In [32]:
empty_uint32 = np.empty(8, dtype='u4')
empty_uint32

array([         0, 1075314688,          0, 1075707904,          0,
       1075838976,          0, 1072693248], dtype=uint32)

### Operations between arrays and scalars

In [33]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [34]:
arr * arr

array([[  1.,   4.,   9.],
       [ 16.,  25.,  36.]])

In [35]:
arr - arr

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [36]:
1 / arr

array([[ 1.    ,  0.5   ,  0.3333],
       [ 0.25  ,  0.2   ,  0.1667]])

In [37]:
arr ** 0.5

array([[ 1.    ,  1.4142,  1.7321],
       [ 2.    ,  2.2361,  2.4495]])

### Basic indexing and slicing

In [43]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
arr[5]

5

In [45]:
arr[5:8]

array([5, 6, 7])

In [46]:
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

- As you can see, if you assign a scalar value to a slice, as in arr[5:8] = 12, the value is propagated (or broadcasted henceforth) to the entire selection. An important first dis- tinction from lists is that array slices are views on the original array.

In [47]:
arr_slice = arr[5:8]
arr_slice[1] = 12345
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,     9])

In [48]:
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [49]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[2]

array([7, 8, 9])

- Thus, individual elements can be accessed recursively. But that is a bit too much work, so you can pass a comma-separated list of indices to select individual elements. So these are equivalent:

In [50]:
arr2d[0][2]

3

In [51]:
arr2d[0, 2]

3

In [ ]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

In [ ]:
arr3d[0]

In [ ]:
old_values = arr3d[0].copy()
arr3d[0] = 42
arr3d
arr3d[0] = old_values
arr3d

In [ ]:
arr3d[1, 0]

#### Indexing with slices

In [ ]:
arr[1:6]

In [ ]:
arr2d
arr2d[:2]

In [ ]:
arr2d[:2, 1:]

In [ ]:
arr2d[1, :2]
arr2d[2, :1]

In [ ]:
arr2d[:, :1]

In [ ]:
arr2d[:2, 1:] = 0

### Boolean indexing

In [ ]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = randn(7, 4)
names
data

In [ ]:
names == 'Bob'

In [ ]:
data[names == 'Bob']

In [ ]:
data[names == 'Bob', 2:]
data[names == 'Bob', 3]

In [ ]:
names != 'Bob'
data[-(names == 'Bob')]

In [ ]:
mask = (names == 'Bob') | (names == 'Will')
mask
data[mask]

In [ ]:
data[data < 0] = 0
data

In [ ]:
data[names != 'Joe'] = 7
data

### Fancy indexing

In [ ]:
arr = np.empty((8, 4))
for i in range(8):
    arr[i] = i
arr

In [ ]:
arr[[4, 3, 0, 6]]

In [ ]:
arr[[-3, -5, -7]]

In [ ]:
# more on reshape in Chapter 12
arr = np.arange(32).reshape((8, 4))
arr
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

In [ ]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

In [ ]:
arr[np.ix_([1, 5, 7, 2], [0, 3, 1, 2])]

### Transposing arrays and swapping axes

In [ ]:
arr = np.arange(15).reshape((3, 5))
arr
arr.T

In [ ]:
arr = np.random.randn(6, 3)
np.dot(arr.T, arr)

In [ ]:
arr = np.arange(16).reshape((2, 2, 4))
arr
arr.transpose((1, 0, 2))

In [ ]:
arr
arr.swapaxes(1, 2)

## Universal Functions: Fast element-wise array functions

In [ ]:
arr = np.arange(10)
np.sqrt(arr)
np.exp(arr)

In [ ]:
x = randn(8)
y = randn(8)
x
y
np.maximum(x, y) # element-wise maximum

In [ ]:
arr = randn(7) * 5
np.modf(arr)

## Data processing using arrays

In [ ]:
points = np.arange(-5, 5, 0.01) # 1000 equally spaced points
xs, ys = np.meshgrid(points, points)
ys

In [ ]:
from matplotlib.pyplot import imshow, title

In [ ]:
import matplotlib.pyplot as plt
z = np.sqrt(xs ** 2 + ys ** 2)
z
plt.imshow(z, cmap=plt.cm.gray); plt.colorbar()
plt.title("Image plot of $\sqrt{x^2 + y^2}$ for a grid of values")

In [ ]:
plt.draw()

### Expressing conditional logic as array operations

In [ ]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

In [ ]:
result = [(x if c else y)
          for x, y, c in zip(xarr, yarr, cond)]
result

In [ ]:
result = np.where(cond, xarr, yarr)
result

In [ ]:
arr = randn(4, 4)
arr
np.where(arr > 0, 2, -2)
np.where(arr > 0, 2, arr) # set only positive values to 2

In [ ]:
# Not to be executed

result = []
for i in range(n):
    if cond1[i] and cond2[i]:
        result.append(0)
    elif cond1[i]:
        result.append(1)
    elif cond2[i]:
        result.append(2)
    else:
        result.append(3)

In [ ]:
# Not to be executed

np.where(cond1 & cond2, 0,
         np.where(cond1, 1,
                  np.where(cond2, 2, 3)))

In [ ]:
# Not to be executed

result = 1 * cond1 + 2 * cond2 + 3 * -(cond1 | cond2)

### Mathematical and statistical methods

In [ ]:
arr = np.random.randn(5, 4) # normally-distributed data
arr.mean()
np.mean(arr)
arr.sum()

In [ ]:
arr.mean(axis=1)
arr.sum(0)

In [ ]:
arr = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
arr.cumsum(0)
arr.cumprod(1)

### Methods for boolean arrays

In [ ]:
arr = randn(100)
(arr > 0).sum() # Number of positive values

In [ ]:
bools = np.array([False, False, True, False])
bools.any()
bools.all()

### Sorting

In [ ]:
arr = randn(8)
arr
arr.sort()
arr

In [ ]:
arr = randn(5, 3)
arr
arr.sort(1)
arr

In [ ]:
large_arr = randn(1000)
large_arr.sort()
large_arr[int(0.05 * len(large_arr))] # 5% quantile

### Unique and other set logic

In [ ]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.unique(names)
ints = np.array([3, 3, 3, 2, 2, 1, 1, 4, 4])
np.unique(ints)

In [ ]:
sorted(set(names))

In [ ]:
values = np.array([6, 0, 0, 3, 2, 5, 6])
np.in1d(values, [2, 3, 6])

## File input and output with arrays

### Storing arrays on disk in binary format

In [ ]:
arr = np.arange(10)
np.save('some_array', arr)

In [ ]:
np.load('some_array.npy')

In [ ]:
np.savez('array_archive.npz', a=arr, b=arr)

In [ ]:
arch = np.load('array_archive.npz')
arch['b']

In [ ]:
!rm some_array.npy
!rm array_archive.npz

### Saving and loading text files

In [ ]:
!cat array_ex.txt

In [ ]:
arr = np.loadtxt('array_ex.txt', delimiter=',')
arr

## Linear algebra

In [ ]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
x
y
x.dot(y)  # equivalently np.dot(x, y)

In [ ]:
np.dot(x, np.ones(3))

In [ ]:
np.random.seed(12345)

In [ ]:
from numpy.linalg import inv, qr
X = randn(5, 5)
mat = X.T.dot(X)
inv(mat)
mat.dot(inv(mat))
q, r = qr(mat)
r

## Random number generation

In [ ]:
samples = np.random.normal(size=(4, 4))
samples

In [ ]:
from random import normalvariate
N = 1000000
%timeit samples = [normalvariate(0, 1) for _ in xrange(N)]
%timeit np.random.normal(size=N)

## Example: Random Walks

In [ ]:
np.random.seed(12345)

In [ ]:
nsteps = 1000
draws = np.random.randint(0, 2, size=nsteps)
steps = np.where(draws > 0, 1, -1)
walk = steps.cumsum()

In [ ]:
walk.min()
walk.max()

In [ ]:
(np.abs(walk) >= 10).argmax()

### Simulating many random walks at once

In [ ]:
nwalks = 5000
nsteps = 1000
draws = np.random.randint(0, 2, size=(nwalks, nsteps)) # 0 or 1
steps = np.where(draws > 0, 1, -1)
walks = steps.cumsum(1)
walks

In [ ]:
walks.max()
walks.min()

In [ ]:
hits30 = (np.abs(walks) >= 30).any(1)
hits30
hits30.sum() # Number that hit 30 or -30

In [ ]:
crossing_times = (np.abs(walks[hits30]) >= 30).argmax(1)
crossing_times.mean()

In [ ]:
steps = np.random.normal(loc=0, scale=0.25,
                         size=(nwalks, nsteps))